version: "3.9"

services:
  db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=tour-of-heroes
    networks:
      - heroes-network
    volumes:
      - ./migration/mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

networks:
  default:
    external:
      name: heroes-network
