apiVersion: apps/v1
kind: Deployment
metadata:
  name: tour-of-heroes-backend
  namespace: heroes-app
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      hostNetwork: true
      containers:
        - name: backend
          image: heroes-api:v1