apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: heroes-app
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - name: backend-http
      port: 8080
      targetPort: 8080
      protocol: TCP
